version: '3'

#Lista de servicios en nuyestro compose
services:
  
  # Este servicio es nuestra aplicacion
  app:
    build:
      context: .
      # Aqui hacemos referencia a la imagen que usamos para este servicio
      dockerfile: Dockerfile
    # El puerto donde lo exponemos
    ports:
      - "8000:8000"
    # Si es que depende de algun otro servicio
    depends_on:
      - db
    
    # Aqui definimos variables que pueden ser utilizadas por la aplicacion y que quedan en el entorno
    environment:
      POSTGRES_URL: postgres://username:password@db:5432/mydatabase

  # Aqui definimos el servicio de base de datos 
  db:
    # La imagen que utilizamos para nuestra DB
    image: postgres:13

    # Aqui creamos las variables que utilizaremos para configurar nuestra imagen
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    
    # Los puertos en que expondremos el servicio
    ports:
      - "5432:5432"
